### ISSUE TITLE
Add sub commands

### ISSUE THREAD

**Issue by Paul2708** [Paul2708/simple-commands#14]
## Description
As some commands need sub commands it would be great to provided them by the framework itself.

## Usage
**Implementation idea**
You could use `@CommandGroup` instead of `@Command`. I do not have any further ideas yet.

**Comment by lineargraph** [comment]
One would probably want a common baseclass for Commands and CommandGroups. One idea would be to have a `call` or `execute` method which in commands just executes the normal command and in a commandgroup would match the first argument against all subcommands and either call one of those commands with the arguments - the first one, or would call a fallback like showing help, or executing another method.
