### ISSUE TITLE
Space missing

### ISSUE THREAD

**Issue by Leon-DE** [Paul2708/simple-commands#25]
## Description
A **space symbol** is mitting in README.md

## To Reproduce
1. Go to https://github.com/Paul2708/simple-commands
2. Click on 'README.md'
3. Scroll down until you reach the end of the file
4. See error 👍 

## Behavior
**Actual behavior**
No space.

**Expected behavior**
See a space.

## Screenshots or log files
![image](https://user-images.githubusercontent.com/47925947/65820695-61dfb500-e22c-11e9-9b23-cae5eb1da042.png)

## Versions
 - Spigot: _1.14.4_
 - simple-command: _0.2.0_

**Comment by Paul2708** [comment]
Hey @Leon-DE.
Thanks for your issue!

I'll fix it later. 💃 

Later.

**Comment by Leon-DE** [comment]
Thanks for your fast answer. Looking forward to see more updates!!!!!

😸 😅
