### ISSUE TITLE
Map language provider

### ISSUE THREAD

**Issue by Paul2708** [Paul2708/simple-commands#65]
## Description
At the moment the default language provider is `LocaleLanguageProvider`. So if you want to send a message via language provider you must declare the message in a message resource file.
If you want to test your code fast, it may be annoying.
So the idea is to declare the messages in the *code* instead of *files*.

## Usage
**Implementation idea**
There is already an interface for `LanguageProvider`.
It could take a `Map<String, String>` that maps the key to the message. In addition the message could also contain object parameters and color codes.

## Alternatives
An alternative would be #54, but it comes with some issues.
The default command arguments hold message resource **keys** for false usage for example.
An identity language provider would return the keys like `argument.boolean.invalid` instead of a fancy message.

**Comment by cerus** [comment]
I'll take care of this if that's okay for you. cc @Paul2708

**Comment by Paul2708** [comment]
I didn't expect any further interest in this project. I'm glad you want to take this issue. Thanks :heart:
Edit: I cannot assign you via mobile app, I will do it later.

**Comment by cerus** [comment]
> One hand washes the other.

;)

**Comment by cerus** [comment]
Just made a pr: #68

**Comment by Paul2708** [comment]
Closed in #68
